version: '3.1'

services:

  web:
    build: ./
    depends_on:
      - server
    volumes:
      - .:/usr/src/app
    ports:
      - "4200:4200"
      - "35730:35730"
    container_name: ember

  server:
      build: ./client
      depends_on:
        - db
      ports:
        - "3000:3000"
      restart: always
      container_name: node_server
      
  db:
    build: ./client/db
    restart: on-failure
    container_name: mysql-db
