version: '3.1'

services:

  # web:
  #   build: ./
  #   depends_on:
  #     - server
  #   volumes:
  #     - .:/usr/src/app
  #   ports:
  #     - 4200:4200
  #     - 35730:35730
  #   container_name: ember

  # sequelize:
  #   build: ./client/db
  #   links:
  #     - db
  #   volumes: 
  #     - .:/sequelize
  #   environment:
  #     SEQ_DB: url-shortner
  #     SEQ_USER: root
  #     SEQ_PW: root

  server:
      build: ./client
      depends_on:
        # - sequelize
        - db
      restart: always
      container_name: node_server
      

  db:
    build: ./client/db
    restart: always
    container_name: mysql-db
  
  # db:
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: url-shortner
  #     MYSQL_USER: root
  #     MYSQL_PW: root
  #   restart: always
  #   ports:
  #       - "6603:3306"
  #   container_name: mysql-db